"""Added vouch_count and Request table

Revision ID: 5fd5adf3ba57
Revises: 
Create Date: 2026-03-22 13:28:45.493853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd5adf3ba57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vouch_count', sa.Integer(), nullable=True))
        batch_op.alter_column('certificate_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('certificate_file',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('vouch_count')

    # ### end Alembic commands ###
