"""Add verification code column

Revision ID: 979dcb104ae4
Revises: 6d9f8488a8e2
Create Date: 2026-03-25 07:29:04.097923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979dcb104ae4'
down_revision = '6d9f8488a8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
